### ISSUE TITLE
High Assurance Rust pdf is unreadable

### ISSUE THREAD

**Issue by pepzi** [shirshak55/Rust-Book-In-PDF#17]
The book High Assurance Rust doesn't seem to have special CSS for printing. I was able to print it manually by resizing my browser window to a narrow window. 

This is a screenshot of what is being generated every day:
![image](https://github.com/shirshak55/Rust-Book-In-PDF/assets/766765/b7cba62c-e0ab-45f0-aa06-78fc2752bc16)

**Comment by shirshak55** [comment]
@pepzi 

I have fixed it.

<img width="1171" alt="image" src="https://github.com/shirshak55/Rust-Book-In-PDF/assets/8097377/aa77e83b-ce8b-4243-8ecf-5f70fc675fe6">

Thank you.
