### ISSUE TITLE
[REQUEST] Add `Node.js to Rust` book

### ISSUE THREAD

**Issue by dalisoft** [shirshak55/Rust-Book-In-PDF#23]
Link https://github.com/jsoverson/node-to-rust

it will be really useful for who comes from Javascript/Node.js

Thank you

**Comment by shirshak55** [comment]
Is it written in mdbook? Also, I am not able to access it.

**Comment by dalisoft** [comment]
@shirshak55 Thank you for reply.
I think no, it is not written in `mdbook`. It uses `make` for build with **Ruby `bundle`**

What shows for you? Page blocked or what shown?
For me like this

![image](https://github.com/shirshak55/Rust-Book-In-PDF/assets/3511344/5fda1e3e-351b-41cf-a6c1-d26d3d5c55a1)

**Comment by shirshak55** [comment]
@dalisoft 

Hi Thank you. 

We need to make a static page, so I can create pdf for it. If someone is willing to do this work, I can include this book in this repo :).

For now closing the issue, feel free to open if there are any updates.

Thanks.
