### ISSUE TITLE
Table of Contents?

### ISSUE THREAD

**Issue by xeruf** [shirshak55/Rust-Book-In-PDF#24]
Thanks for making these PDFs! Would it be possible to add a table of contents to them?

**Comment by shirshak55** [comment]
@xeruf thanks for the feedback. I can try generating table of contents based on headers.

**Comment by alande-amorim** [comment]
@shirshak55 Any updates on this? I want to print The Book and it would be nice to have the table of contents. Thanks!

**Comment by shirshak55** [comment]
@alande-amorim  I will try working on it next week. 

Thanks.

**Comment by shirshak55** [comment]
Sorry for the delay. I have tried my best to add table of contents.

Let me know if it works for you :)
https://github.com/shirshak55/Rust-Book-In-PDF/releases


PR:
https://github.com/shirshak55/Rust-Book-In-PDF/pull/25
